name: Cpp package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Apt get
        run: |
          sudo apt-get install gcc git cmake -y
      - name: Cache Catch2
        id: cache-catch2
        uses: actions/cache@v3
        with:
          path: usr/local/include/catch2
          key: catch2
      - name: Get Catch2
        if: steps.cache-catch2.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          git checkout v3.3.2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Run
        run: |
          cd build
          ./Vector
